# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
#    parameter_name: value

services:
# yml dosyaları 4 boşlık yada tab ile kullanılır
    pd.request.json_transformer:
        class: VanBundle\Listener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

